name: Deploy to Azure
on:
  push:
    branches:
      - main
workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      BACKEND_RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP }}
      BACKEND_STORAGE_ACCOUNT: ${{ secrets.STORAGE_ACCOUNT }}
      BACKEND_CONTAINER_NAME: ${{ secrets.CONTAINER_NAME }}
      TF_VERSION: 1.3.6

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: 'Terraform Lint Check'
        run: |
          make tf-lint

      - name: 'Terraform Init'
        run: |
          make tf-init

      - name: 'Terraform Plan'
        env:
          TF_VAR_OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          TF_VAR_OPENAI_API_URL: ${{ secrets.OPENAI_API_URL }}
        run: |
          make tf-plan

      - name: 'Terraform Apply'
        if: github.event_name != 'pull_request'
        run: |
          make tf-apply
